### ISSUE TITLE
(node:77781) UnhandledPromiseRejectionWarning: Error: Non-whitespace before first tag.

### ISSUE THREAD

**Issue by adamantine-dev** [scolladon/sfdc-generate-package#9]
Hi Sebastien.

I've faced issue:

```
(node:77781) UnhandledPromiseRejectionWarning: Error: Non-whitespace before first tag.
Line: 0
Column: 1
Char: 
    at error (/usr/local/lib/node_modules/sfdc-generate-package/node_modules/sax/lib/sax.js:651:10)
    at strictFail (/usr/local/lib/node_modules/sfdc-generate-package/node_modules/sax/lib/sax.js:677:7)
    at beginWhiteSpace (/usr/local/lib/node_modules/sfdc-generate-package/node_modules/sax/lib/sax.js:951:7)
    at SAXParser.write (/usr/local/lib/node_modules/sfdc-generate-package/node_modules/sax/lib/sax.js:1006:11)
    at Parser.exports.Parser.Parser.parseString (/usr/local/lib/node_modules/sfdc-generate-package/node_modules/xml2js/lib/parser.js:322:31)
    at Parser.parseString (/usr/local/lib/node_modules/sfdc-generate-package/node_modules/xml2js/lib/parser.js:5:59)
    at Promise (/usr/local/lib/node_modules/sfdc-generate-package/lib/utils/async-xml-parser.js:6:12)
    at new Promise (<anonymous>)
    at parseStringAsync (/usr/local/lib/node_modules/sfdc-generate-package/lib/utils/async-xml-parser.js:4:19)
(node:77781) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:77781) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Looks like an issue in libraries that you've used.
But maybe you know how to resolve it quickly.

Thanks! :)

**Comment by scolladon** [comment]
change the content of the file lib/utils/async-xml-parser.js in your node_modules folder with the following one and tell me if it worked :

`
const xml2js = require('xml2js');

const parseStringAsync = (file) => {
  const promise = new Promise((resolve, reject) => {
    const parser = new xml2js.Parser();
    let content = file.content.replace('\ufeff', '');
    parser.parseString(content, (err, result) => {
      if (err) reject(err);
      file.content = result;
      resolve(file);
    });
  });
  return promise;
};
module.exports = parseStringAsync;
`

**Comment by adamantine-dev** [comment]
Nope, the same issue.

```
(node:78224) UnhandledPromiseRejectionWarning: Error: Non-whitespace before first tag.
Line: 0
Column: 1
Char: 
    at error (/usr/local/lib/node_modules/sfdc-generate-package/node_modules/sax/lib/sax.js:651:10)
    at strictFail (/usr/local/lib/node_modules/sfdc-generate-package/node_modules/sax/lib/sax.js:677:7)
    at beginWhiteSpace (/usr/local/lib/node_modules/sfdc-generate-package/node_modules/sax/lib/sax.js:951:7)
    at SAXParser.write (/usr/local/lib/node_modules/sfdc-generate-package/node_modules/sax/lib/sax.js:1006:11)
    at Parser.exports.Parser.Parser.parseString (/usr/local/lib/node_modules/sfdc-generate-package/node_modules/xml2js/lib/parser.js:322:31)
    at Parser.parseString (/usr/local/lib/node_modules/sfdc-generate-package/node_modules/xml2js/lib/parser.js:5:59)
    at Promise (/usr/local/lib/node_modules/sfdc-generate-package/lib/utils/async-xml-parser.js:22:10)
    at new Promise (<anonymous>)
    at parseStringAsync (/usr/local/lib/node_modules/sfdc-generate-package/lib/utils/async-xml-parser.js:19:18)
(node:78224) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:78224) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by adamantine-dev** [comment]
Interesting, but it doesn't work even for files that I've already parsed today and last week.
I didn't update any npm package, I didn't update my source files that should be parsed.
It just worked few days, today and stopped work at some point. I don't know why.
Very strange behavior.

**Comment by scolladon** [comment]
weird, did you try to reinstall ? (dump node_modules and rerun npm install)

**Comment by adamantine-dev** [comment]
Yes, I did it several times.

**Comment by adamantine-dev** [comment]
Hmm... Looks like I've resolved the issue in a strange way.

I've removed an _sfdc-generate-package_, then I've installed an _sfdc-git-package_.
After it, I've removed the _sfdc-git-package_ and installed the _sfdc-generate-package back_.
And it works!

**Comment by scolladon** [comment]
lol !
good job and thanks for the feedback

**Comment by adamantine-dev** [comment]
Btw, you should use a package _sfdc-git-package_ at least one time with a command something like:

```
sgp -f 92ac72f -t 2904c64 -a 43.0 -r ./
```

And only after it you should remove the _sfdc-git-package_ package and install _sfdc-generate-package_.
